// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'my_shift_plan_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

MyShiftPlanModel _$MyShiftPlanModelFromJson(Map<String, dynamic> json) =>
    MyShiftPlanModel(
      id: json['id'] as String?,
      agencyId: json['agencyId'] as String?,
      agencyCode: json['agencyCode'] as String?,
      agencyName: json['agencyName'] as String?,
      officeTimeCode: json['officeTimeCode'] as String?,
      officeTimeName: json['officeTimeName'] as String?,
      isSunOfficeDay: json['isSunOfficeDay'] as bool?,
      isMonOfficeDay: json['isMonOfficeDay'] as bool?,
      isTuesOfficeDay: json['isTuesOfficeDay'] as bool?,
      isWedOfficeDay: json['isWedOfficeDay'] as bool?,
      isThursOfficeDay: json['isThursOfficeDay'] as bool?,
      isFriOfficeDay: json['isFriOfficeDay'] as bool?,
      isSatOfficeDay: json['isSatOfficeDay'] as bool?,
      sunStartTime: json['sunStartTime'] as String?,
      sunEndTime: json['sunEndTime'] as String?,
      monStartTime: json['monStartTime'] as String?,
      monEndTime: json['monEndTime'] as String?,
      tuesStartTime: json['tuesStartTime'] as String?,
      tuesEndTime: json['tuesEndTime'] as String?,
      wedStartTime: json['wedStartTime'] as String?,
      wedEndTime: json['wedEndTime'] as String?,
      thursStartTime: json['thursStartTime'] as String?,
      thursEndTime: json['thursEndTime'] as String?,
      friStartTime: json['friStartTime'] as String?,
      friEndTime: json['friEndTime'] as String?,
      satStartTime: json['satStartTime'] as String?,
      satEndTime: json['satEndTime'] as String?,
      lateTime: (json['lateTime'] as num?)?.toDouble(),
      absentTime: (json['absentTime'] as num?)?.toDouble(),
      lateMarks: (json['lateMarks'] as num?)?.toDouble(),
      absentMarks: (json['absentMarks'] as num?)?.toDouble(),
      deductionLeaveLate: json['deductionLeaveLate'] as bool?,
      deductionLeaveAbsent: json['deductionLeaveAbsent'] as bool?,
      otStartTime: (json['otStartTime'] as num?)?.toDouble(),
      defultShift: json['defultShift'] as int?,
      tuesOfficeDay: json['tuesOfficeDay'] as bool?,
      wedOfficeDay: json['wedOfficeDay'] as bool?,
      thursOfficeDay: json['thursOfficeDay'] as bool?,
      friOfficeDay: json['friOfficeDay'] as bool?,
      satOfficeDay: json['satOfficeDay'] as bool?,
      sunNextDay: json['sunNextDay'] as bool?,
      monNextDay: json['monNextDay'] as bool?,
      tuesNextDay: json['tuesNextDay'] as bool?,
      wedNextDay: json['wedNextDay'] as bool?,
      thursNextDay: json['thursNextDay'] as bool?,
      friNextDay: json['friNextDay'] as bool?,
      satNextDay: json['satNextDay'] as bool?,
      sunOfficeDay: json['sunOfficeDay'] as bool?,
      monOfficeDay: json['monOfficeDay'] as bool?,
    );

Map<String, dynamic> _$MyShiftPlanModelToJson(MyShiftPlanModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'agencyId': instance.agencyId,
      'agencyCode': instance.agencyCode,
      'agencyName': instance.agencyName,
      'officeTimeCode': instance.officeTimeCode,
      'officeTimeName': instance.officeTimeName,
      'isSunOfficeDay': instance.isSunOfficeDay,
      'isMonOfficeDay': instance.isMonOfficeDay,
      'isTuesOfficeDay': instance.isTuesOfficeDay,
      'isWedOfficeDay': instance.isWedOfficeDay,
      'isThursOfficeDay': instance.isThursOfficeDay,
      'isFriOfficeDay': instance.isFriOfficeDay,
      'isSatOfficeDay': instance.isSatOfficeDay,
      'sunStartTime': instance.sunStartTime,
      'sunEndTime': instance.sunEndTime,
      'monStartTime': instance.monStartTime,
      'monEndTime': instance.monEndTime,
      'tuesStartTime': instance.tuesStartTime,
      'tuesEndTime': instance.tuesEndTime,
      'wedStartTime': instance.wedStartTime,
      'wedEndTime': instance.wedEndTime,
      'thursStartTime': instance.thursStartTime,
      'thursEndTime': instance.thursEndTime,
      'friStartTime': instance.friStartTime,
      'friEndTime': instance.friEndTime,
      'satStartTime': instance.satStartTime,
      'satEndTime': instance.satEndTime,
      'lateTime': instance.lateTime,
      'absentTime': instance.absentTime,
      'lateMarks': instance.lateMarks,
      'absentMarks': instance.absentMarks,
      'deductionLeaveLate': instance.deductionLeaveLate,
      'deductionLeaveAbsent': instance.deductionLeaveAbsent,
      'otStartTime': instance.otStartTime,
      'defultShift': instance.defultShift,
      'tuesOfficeDay': instance.tuesOfficeDay,
      'wedOfficeDay': instance.wedOfficeDay,
      'thursOfficeDay': instance.thursOfficeDay,
      'friOfficeDay': instance.friOfficeDay,
      'satOfficeDay': instance.satOfficeDay,
      'sunNextDay': instance.sunNextDay,
      'monNextDay': instance.monNextDay,
      'tuesNextDay': instance.tuesNextDay,
      'wedNextDay': instance.wedNextDay,
      'thursNextDay': instance.thursNextDay,
      'friNextDay': instance.friNextDay,
      'satNextDay': instance.satNextDay,
      'sunOfficeDay': instance.sunOfficeDay,
      'monOfficeDay': instance.monOfficeDay,
    };
