// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'officer_search_view_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

OfficerSearchViewModel _$OfficerSearchViewModelFromJson(
        Map<String, dynamic> json) =>
    OfficerSearchViewModel(
      createdByUsername: json['createdByUsername'] as String?,
      createdByFullname: json['createdByFullname'] as String?,
      createdByEmail: json['createdByEmail'] as String?,
      createdByMobile: json['createdByMobile'] as String?,
      createdOn: json['createdOn'] as String?,
      createdAt: json['createdAt'] as String?,
      updatedByUsername: json['updatedByUsername'],
      updatedByFullname: json['updatedByFullname'],
      updatedByEmail: json['updatedByEmail'],
      updatedByMobile: json['updatedByMobile'],
      updatedOn: json['updatedOn'],
      updatedAt: json['updatedAt'],
      approvedByUsername: json['approvedByUsername'],
      approvedByFullname: json['approvedByFullname'],
      approvedByEmail: json['approvedByEmail'],
      approvedByMobile: json['approvedByMobile'],
      approvedOn: json['approvedOn'],
      approvedAt: json['approvedAt'],
      id: json['id'] as String?,
      countryId: json['countryId'] as String?,
      countryCode: json['countryCode'] as String?,
      countryName: json['countryName'],
      agencyId: json['agencyId'] as String?,
      agencyCode: json['agencyCode'] as String?,
      agencyName: json['agencyName'] as String?,
      unitId: json['unitId'] as String?,
      unitCode: json['unitCode'] as String?,
      unitName: json['unitName'] as String?,
      locationId: json['locationId'] as String?,
      locationCode: json['locationCode'] as String?,
      locationName: json['locationName'] as String?,
      address: json['address'] as String?,
      userId: json['userId'] as String?,
      username: json['username'] as String?,
      fullname: json['fullname'] as String?,
      phone: json['phone'],
      mobile: json['mobile'] as String?,
      email: json['email'] as String?,
      gender: json['gender'] as String?,
      officeLatitude: (json['officeLatitude'] as num?)?.toDouble(),
      officeLongitude: (json['officeLongitude'] as num?)?.toDouble(),
      reportingManagerId: json['reportingManagerId'] as String?,
      reportingManagerUsername: json['reportingManagerUsername'] as String?,
      reportingManagerFullname: json['reportingManagerFullname'] as String?,
      reportingManagerGender: json['reportingManagerGender'],
      reportingManagerEmail: json['reportingManagerEmail'] as String?,
      reportingManagerMobile: json['reportingManagerMobile'] as String?,
      reportingManagerRole: json['reportingManagerRole'] as String?,
      reportingManagerRoleLevel: json['reportingManagerRoleLevel'] as int?,
      reportingManagerRoleGroup: json['reportingManagerRoleGroup'] as String?,
      reportingManagerRoleGroupLevel:
          json['reportingManagerRoleGroupLevel'] as int?,
      geographyPoint: json['geographyPoint'],
      roleModel: json['roleModel'],
      employeeRoleModel: json['employeeRoleModel'],
      userInfo: json['userInfo'],
      approved: json['approved'] as bool?,
    );

Map<String, dynamic> _$OfficerSearchViewModelToJson(
        OfficerSearchViewModel instance) =>
    <String, dynamic>{
      'createdByUsername': instance.createdByUsername,
      'createdByFullname': instance.createdByFullname,
      'createdByEmail': instance.createdByEmail,
      'createdByMobile': instance.createdByMobile,
      'createdOn': instance.createdOn,
      'createdAt': instance.createdAt,
      'updatedByUsername': instance.updatedByUsername,
      'updatedByFullname': instance.updatedByFullname,
      'updatedByEmail': instance.updatedByEmail,
      'updatedByMobile': instance.updatedByMobile,
      'updatedOn': instance.updatedOn,
      'updatedAt': instance.updatedAt,
      'approvedByUsername': instance.approvedByUsername,
      'approvedByFullname': instance.approvedByFullname,
      'approvedByEmail': instance.approvedByEmail,
      'approvedByMobile': instance.approvedByMobile,
      'approvedOn': instance.approvedOn,
      'approvedAt': instance.approvedAt,
      'id': instance.id,
      'countryId': instance.countryId,
      'countryCode': instance.countryCode,
      'countryName': instance.countryName,
      'agencyId': instance.agencyId,
      'agencyCode': instance.agencyCode,
      'agencyName': instance.agencyName,
      'unitId': instance.unitId,
      'unitCode': instance.unitCode,
      'unitName': instance.unitName,
      'locationId': instance.locationId,
      'locationCode': instance.locationCode,
      'locationName': instance.locationName,
      'address': instance.address,
      'userId': instance.userId,
      'username': instance.username,
      'fullname': instance.fullname,
      'phone': instance.phone,
      'mobile': instance.mobile,
      'email': instance.email,
      'gender': instance.gender,
      'officeLatitude': instance.officeLatitude,
      'officeLongitude': instance.officeLongitude,
      'reportingManagerId': instance.reportingManagerId,
      'reportingManagerUsername': instance.reportingManagerUsername,
      'reportingManagerFullname': instance.reportingManagerFullname,
      'reportingManagerGender': instance.reportingManagerGender,
      'reportingManagerEmail': instance.reportingManagerEmail,
      'reportingManagerMobile': instance.reportingManagerMobile,
      'reportingManagerRole': instance.reportingManagerRole,
      'reportingManagerRoleLevel': instance.reportingManagerRoleLevel,
      'reportingManagerRoleGroup': instance.reportingManagerRoleGroup,
      'reportingManagerRoleGroupLevel': instance.reportingManagerRoleGroupLevel,
      'geographyPoint': instance.geographyPoint,
      'roleModel': instance.roleModel,
      'employeeRoleModel': instance.employeeRoleModel,
      'userInfo': instance.userInfo,
      'approved': instance.approved,
    };
