// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'usermodel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ProfileUserModel _$ProfileUserModelFromJson(Map<String, dynamic> json) =>
    ProfileUserModel(
      countryId: json['countryId'] as String?,
      countryCode: json['countryCode'] as String?,
      countryName: json['countryName'] as String?,
      countryTelcode: json['countryTelcode'] as String?,
      geoLevel0Type: json['geoLevel0Type'] as String?,
      geoLevel1Id: json['geoLevel1Id'] as String?,
      geoLevel1Code: json['geoLevel1Code'] as String?,
      geoLevel1Name: json['geoLevel1Name'] as String?,
      geoLevel1Type: json['geoLevel1Type'] as String?,
      geoLevel2Id: json['geoLevel2Id'] as String?,
      geoLevel2Code: json['geoLevel2Code'] as String?,
      geoLevel2Name: json['geoLevel2Name'] as String?,
      geoLevel2Type: json['geoLevel2Type'] as String?,
      geoLevel3Id: json['geoLevel3Id'] as String?,
      geoLevel3Code: json['geoLevel3Code'] as String?,
      geoLevel3Name: json['geoLevel3Name'] as String?,
      geoLevel3Type: json['geoLevel3Type'] as String?,
      geoLevel4Id: json['geoLevel4Id'] as String?,
      geoLevel4Code: json['geoLevel4Code'] as String?,
      geoLevel4Name: json['geoLevel4Name'] as String?,
      geoLevel4Type: json['geoLevel4Type'] as String?,
      geoLevel5Id: json['geoLevel5Id'] as String?,
      geoLevel5Code: json['geoLevel5Code'] as String?,
      geoLevel5Name: json['geoLevel5Name'] as String?,
      geoLevel5Type: json['geoLevel5Type'] as String?,
      geoLevel6Id: json['geoLevel6Id'] as String?,
      geoLevel6Code: json['geoLevel6Code'] as String?,
      geoLevel6Name: json['geoLevel6Name'] as String?,
      geoLevel6Type: json['geoLevel6Type'] as String?,
      geoLevel7Id: json['geoLevel7Id'] as String?,
      geoLevel7Code: json['geoLevel7Code'] as String?,
      geoLevel7Name: json['geoLevel7Name'] as String?,
      geoLevel7Type: json['geoLevel7Type'] as String?,
      geoLevel8Id: json['geoLevel8Id'] as String?,
      geoLevel8Code: json['geoLevel8Code'] as String?,
      geoLevel8Name: json['geoLevel8Name'] as String?,
      geoLevel8Type: json['geoLevel8Type'] as String?,
      geoLevel9Id: json['geoLevel9Id'] as String?,
      geoLevel9Code: json['geoLevel9Code'] as String?,
      geoLevel9Name: json['geoLevel9Name'] as String?,
      geoLevel9Type: json['geoLevel9Type'] as String?,
      highestLevelImplemented: json['highestLevelImplemented'] as int?,
      geoLevelId: json['geoLevelId'] as String?,
      geoLevelCode: json['geoLevelCode'] as String?,
      geoLevelName: json['geoLevelName'] as String?,
      levelType: json['levelType'] as String?,
      areaLevelFullCode: json['areaLevelFullCode'] as String?,
      id: json['id'] as String?,
      username: json['username'] as String?,
      personName: json['personName'] as String?,
      gender: json['gender'] as String?,
      email: json['email'] as String?,
      mobile: json['mobile'] as String?,
      fatherName: json['fatherName'] as String?,
      motherName: json['motherName'] as String?,
      birthDate: json['birthDate'] as String?,
      birthPlace: json['birthPlace'] as String?,
      signupDate: json['signupDate'] as String?,
      occupation: json['occupation'] as String?,
      organizationName: json['organizationName'] as String?,
      desig: json['desig'] as String?,
      bloodGroup: json['bloodGroup'] as String?,
      homeLatitude: (json['homeLatitude'] as num?)?.toDouble(),
      homeLongitude: (json['homeLongitude'] as num?)?.toDouble(),
      homeAddress: json['homeAddress'] as String?,
      permanentAddress: json['permanentAddress'] as String?,
      currentLatitude: (json['currentLatitude'] as num?)?.toDouble(),
      currentLongitude: (json['currentLongitude'] as num?)?.toDouble(),
      currentLocationUpdatedOn: json['currentLocationUpdatedOn'] as String?,
      currentLocationUpdatedAt: json['currentLocationUpdatedAt'] as String?,
      officeLatitude: (json['officeLatitude'] as num?)?.toDouble(),
      officeLongitude: (json['officeLongitude'] as num?)?.toDouble(),
      officeAddress: json['officeAddress'] as String?,
      nidNo: json['nidNo'] as String?,
      nidNoVerifiedDate: json['nidNoVerifiedDate'] as String?,
      nidNoVerificationResponse: json['nidNoVerificationResponse'] as String?,
      passportNo: json['passportNo'] as String?,
      passportIssuePlace: json['passportIssuePlace'] as String?,
      nationality: json['nationality'] as String?,
      passportIssueDate: json['passportIssueDate'] as String?,
      passportExpiredDate: json['passportExpiredDate'] as String?,
      passportDocVerifiedDate: json['passportDocVerifiedDate'] as String?,
      passportDocVerificationResponse:
          json['passportDocVerificationResponse'] as String?,
      licenseNo: json['licenseNo'] as String?,
      licenseAuthority: json['licenseAuthority'] as String?,
      licenseIssueDate: json['licenseIssueDate'] as String?,
      licenseExpiredDate: json['licenseExpiredDate'] as String?,
      licenseType: json['licenseType'] as String?,
      licenseAllowedVehicle: json['licenseAllowedVehicle'] as String?,
      birthCertNo: json['birthCertNo'] as String?,
      birthCertDocVerifiedDate: json['birthCertDocVerifiedDate'] as String?,
      birthCertDocVerificationResponse:
          json['birthCertDocVerificationResponse'] as String?,
      taxNo: json['taxNo'] as String?,
      taxZone: json['taxZone'] as String?,
      taxCircle: json['taxCircle'] as String?,
      taxDocVerifiedDate: json['taxDocVerifiedDate'] as String?,
      taxDocVerificationResponse: json['taxDocVerificationResponse'] as String?,
      sscPassYear: json['sscPassYear'] as int?,
      schoolName: json['schoolName'] as String?,
      sscGroup: json['sscGroup'] as String?,
      sscCertificateSerialNo: json['sscCertificateSerialNo'] as String?,
      sscCertVerifiedDate: json['sscCertVerifiedDate'] as String?,
      sscCertVerificationResponse:
          json['sscCertVerificationResponse'] as String?,
      hscYear: json['hscYear'] as int?,
      collegeName: json['collegeName'] as String?,
      hscGroup: json['hscGroup'] as String?,
      hscCertificateSerialNo: json['hscCertificateSerialNo'] as String?,
      hscCertVerifiedDate: json['hscCertVerifiedDate'] as String?,
      hscCertVerificationResponse:
          json['hscCertVerificationResponse'] as String?,
      bachelorPassYear: json['bachelorPassYear'] as int?,
      bachelorUniversityName: json['bachelorUniversityName'] as String?,
      bachelorSubjectName: json['bachelorSubjectName'] as String?,
      bachelorCertificateSerialNo:
          json['bachelorCertificateSerialNo'] as String?,
      bachelorCertVerifiedDate: json['bachelorCertVerifiedDate'] as String?,
      bachelorCertVerificationResponse:
          json['bachelorCertVerificationResponse'] as String?,
      mastersPassYear: json['mastersPassYear'] as int?,
      mastersUniversityName: json['mastersUniversityName'] as String?,
      mastersSubjectName: json['mastersSubjectName'] as String?,
      mastersCertificateSerialNo: json['mastersCertificateSerialNo'] as String?,
      mastersCertVerifiedDate: json['mastersCertVerifiedDate'] as String?,
      mastersCertVerificationResponse:
          json['mastersCertVerificationResponse'] as String?,
      spouseUsername: json['spouseUsername'] as String?,
      spouseName: json['spouseName'] as String?,
      spouseMobile: json['spouseMobile'] as String?,
      spouseEmail: json['spouseEmail'] as String?,
      spouseBirthDate: json['spouseBirthDate'] as String?,
      geographyType: json['geographyType'] as String?,
      dataDigest: json['dataDigest'] as String?,
      authenticationLevel: json['authenticationLevel'] as int?,
      surveyRole: json['surveyRole'] as String?,
      surveyManagerUsername: json['surveyManagerUsername'] as String?,
      otpValue: json['otpValue'] as String?,
      otpCreatedDate: json['otpCreatedDate'] as String?,
      otpCreatedAt: json['otpCreatedAt'] as String?,
      otpExpiredDate: json['otpExpiredDate'] as String?,
      otpExpiredAt: json['otpExpiredAt'] as String?,
      countOtpUse: json['countOtpUse'] as int?,
      fatherUsername: json['fatherUsername'] as String?,
      motherUsername: json['motherUsername'] as String?,
      personNameLocalLang: json['personNameLocalLang'] as String?,
      fatherNameLocalLang: json['fatherNameLocalLang'] as String?,
      motherNameLocalLang: json['motherNameLocalLang'] as String?,
      roles: json['roles'] as String?,
      roleGroup: json['roleGroup'] as String?,
      roleGroupLevel: json['roleGroupLevel'] as int?,
      roleLevel: json['roleLevel'] as int?,
      role: json['role'] as String?,
      dirtyVersion: json['dirtyVersion'] as int?,
      appToken: json['appToken'] as String?,
      appTokenCreatedAt: json['appTokenCreatedAt'] as String?,
      appTokenCreatedOn: json['appTokenCreatedOn'] as String?,
      userImg: json['userImg'] as String?,
      userHashInfo: json['userHashInfo'] as String?,
      userImgHash: json['userImgHash'] as String?,
      nidStatus: json['nidStatus'] as int?,
      passportStatus: json['passportStatus'] as int?,
      mastersCertificateStatus: json['mastersCertificateStatus'] as int?,
      bachelorCertificateStatus: json['bachelorCertificateStatus'] as int?,
      hscCertificateStatus: json['hscCertificateStatus'] as int?,
      sscCertificateStatus: json['sscCertificateStatus'] as int?,
      birthCertificateStatus: json['birthCertificateStatus'] as int?,
      tinCertificateStatus: json['tinCertificateStatus'] as int?,
      drivingLicenseStatus: json['drivingLicenseStatus'] as int?,
      pointOffice: json['pointOffice'] as String?,
      pointResidence: json['pointResidence'] as String?,
      pointHome: json['pointHome'] as String?,
      masterViewModel: json['masterViewModel'] as String?,
      employeeRole: json['employeeRole'] as String?,
      enabled: json['enabled'] as bool?,
      active: json['active'] as bool?,
      publicUser: json['publicUser'] as bool?,
      locationTraceEnabled: json['locationTraceEnabled'] as bool?,
      nidDocUploaded: json['nidDocUploaded'] as bool?,
      taxDocUploaded: json['taxDocUploaded'] as bool?,
      passportDocUploaded: json['passportDocUploaded'] as bool?,
      sscCertUploaded: json['sscCertUploaded'] as bool?,
      hscCertUploaded: json['hscCertUploaded'] as bool?,
      bachelorCertUploaded: json['bachelorCertUploaded'] as bool?,
      mastersCertUploaded: json['mastersCertUploaded'] as bool?,
      nidNoVerified: json['nidNoVerified'] as bool?,
      passportNoVerified: json['passportNoVerified'] as bool?,
      licenseDocUploaded: json['licenseDocUploaded'] as bool?,
      licenseNoVerified: json['licenseNoVerified'] as bool?,
      birthCertDocUploaded: json['birthCertDocUploaded'] as bool?,
      birthCertNoVerified: json['birthCertNoVerified'] as bool?,
      taxNoVerified: json['taxNoVerified'] as bool?,
      sscCertVerified: json['sscCertVerified'] as bool?,
      hscCertVerified: json['hscCertVerified'] as bool?,
      bachelorCertVerified: json['bachelorCertVerified'] as bool?,
      mastersCertVerified: json['mastersCertVerified'] as bool?,
      employed: json['employed'] as bool?,
      sscCompleted: json['sscCompleted'] as bool?,
      hscCompleted: json['hscCompleted'] as bool?,
      bachelorCompleted: json['bachelorCompleted'] as bool?,
      mastersCompleted: json['mastersCompleted'] as bool?,
    );

Map<String, dynamic> _$ProfileUserModelToJson(ProfileUserModel instance) =>
    <String, dynamic>{
      'countryId': instance.countryId,
      'countryCode': instance.countryCode,
      'countryName': instance.countryName,
      'countryTelcode': instance.countryTelcode,
      'geoLevel0Type': instance.geoLevel0Type,
      'geoLevel1Id': instance.geoLevel1Id,
      'geoLevel1Code': instance.geoLevel1Code,
      'geoLevel1Name': instance.geoLevel1Name,
      'geoLevel1Type': instance.geoLevel1Type,
      'geoLevel2Id': instance.geoLevel2Id,
      'geoLevel2Code': instance.geoLevel2Code,
      'geoLevel2Name': instance.geoLevel2Name,
      'geoLevel2Type': instance.geoLevel2Type,
      'geoLevel3Id': instance.geoLevel3Id,
      'geoLevel3Code': instance.geoLevel3Code,
      'geoLevel3Name': instance.geoLevel3Name,
      'geoLevel3Type': instance.geoLevel3Type,
      'geoLevel4Id': instance.geoLevel4Id,
      'geoLevel4Code': instance.geoLevel4Code,
      'geoLevel4Name': instance.geoLevel4Name,
      'geoLevel4Type': instance.geoLevel4Type,
      'geoLevel5Id': instance.geoLevel5Id,
      'geoLevel5Code': instance.geoLevel5Code,
      'geoLevel5Name': instance.geoLevel5Name,
      'geoLevel5Type': instance.geoLevel5Type,
      'geoLevel6Id': instance.geoLevel6Id,
      'geoLevel6Code': instance.geoLevel6Code,
      'geoLevel6Name': instance.geoLevel6Name,
      'geoLevel6Type': instance.geoLevel6Type,
      'geoLevel7Id': instance.geoLevel7Id,
      'geoLevel7Code': instance.geoLevel7Code,
      'geoLevel7Name': instance.geoLevel7Name,
      'geoLevel7Type': instance.geoLevel7Type,
      'geoLevel8Id': instance.geoLevel8Id,
      'geoLevel8Code': instance.geoLevel8Code,
      'geoLevel8Name': instance.geoLevel8Name,
      'geoLevel8Type': instance.geoLevel8Type,
      'geoLevel9Id': instance.geoLevel9Id,
      'geoLevel9Code': instance.geoLevel9Code,
      'geoLevel9Name': instance.geoLevel9Name,
      'geoLevel9Type': instance.geoLevel9Type,
      'highestLevelImplemented': instance.highestLevelImplemented,
      'geoLevelId': instance.geoLevelId,
      'geoLevelCode': instance.geoLevelCode,
      'geoLevelName': instance.geoLevelName,
      'levelType': instance.levelType,
      'areaLevelFullCode': instance.areaLevelFullCode,
      'id': instance.id,
      'username': instance.username,
      'personName': instance.personName,
      'gender': instance.gender,
      'email': instance.email,
      'mobile': instance.mobile,
      'fatherName': instance.fatherName,
      'motherName': instance.motherName,
      'birthDate': instance.birthDate,
      'birthPlace': instance.birthPlace,
      'signupDate': instance.signupDate,
      'occupation': instance.occupation,
      'organizationName': instance.organizationName,
      'desig': instance.desig,
      'bloodGroup': instance.bloodGroup,
      'homeLatitude': instance.homeLatitude,
      'homeLongitude': instance.homeLongitude,
      'homeAddress': instance.homeAddress,
      'permanentAddress': instance.permanentAddress,
      'currentLatitude': instance.currentLatitude,
      'currentLongitude': instance.currentLongitude,
      'currentLocationUpdatedOn': instance.currentLocationUpdatedOn,
      'currentLocationUpdatedAt': instance.currentLocationUpdatedAt,
      'officeLatitude': instance.officeLatitude,
      'officeLongitude': instance.officeLongitude,
      'officeAddress': instance.officeAddress,
      'nidNo': instance.nidNo,
      'nidNoVerifiedDate': instance.nidNoVerifiedDate,
      'nidNoVerificationResponse': instance.nidNoVerificationResponse,
      'passportNo': instance.passportNo,
      'passportIssuePlace': instance.passportIssuePlace,
      'nationality': instance.nationality,
      'passportIssueDate': instance.passportIssueDate,
      'passportExpiredDate': instance.passportExpiredDate,
      'passportDocVerifiedDate': instance.passportDocVerifiedDate,
      'passportDocVerificationResponse':
          instance.passportDocVerificationResponse,
      'licenseNo': instance.licenseNo,
      'licenseAuthority': instance.licenseAuthority,
      'licenseIssueDate': instance.licenseIssueDate,
      'licenseExpiredDate': instance.licenseExpiredDate,
      'licenseType': instance.licenseType,
      'licenseAllowedVehicle': instance.licenseAllowedVehicle,
      'birthCertNo': instance.birthCertNo,
      'birthCertDocVerifiedDate': instance.birthCertDocVerifiedDate,
      'birthCertDocVerificationResponse':
          instance.birthCertDocVerificationResponse,
      'taxNo': instance.taxNo,
      'taxZone': instance.taxZone,
      'taxCircle': instance.taxCircle,
      'taxDocVerifiedDate': instance.taxDocVerifiedDate,
      'taxDocVerificationResponse': instance.taxDocVerificationResponse,
      'sscPassYear': instance.sscPassYear,
      'schoolName': instance.schoolName,
      'sscGroup': instance.sscGroup,
      'sscCertificateSerialNo': instance.sscCertificateSerialNo,
      'sscCertVerifiedDate': instance.sscCertVerifiedDate,
      'sscCertVerificationResponse': instance.sscCertVerificationResponse,
      'hscYear': instance.hscYear,
      'collegeName': instance.collegeName,
      'hscGroup': instance.hscGroup,
      'hscCertificateSerialNo': instance.hscCertificateSerialNo,
      'hscCertVerifiedDate': instance.hscCertVerifiedDate,
      'hscCertVerificationResponse': instance.hscCertVerificationResponse,
      'bachelorPassYear': instance.bachelorPassYear,
      'bachelorUniversityName': instance.bachelorUniversityName,
      'bachelorSubjectName': instance.bachelorSubjectName,
      'bachelorCertificateSerialNo': instance.bachelorCertificateSerialNo,
      'bachelorCertVerifiedDate': instance.bachelorCertVerifiedDate,
      'bachelorCertVerificationResponse':
          instance.bachelorCertVerificationResponse,
      'mastersPassYear': instance.mastersPassYear,
      'mastersUniversityName': instance.mastersUniversityName,
      'mastersSubjectName': instance.mastersSubjectName,
      'mastersCertificateSerialNo': instance.mastersCertificateSerialNo,
      'mastersCertVerifiedDate': instance.mastersCertVerifiedDate,
      'mastersCertVerificationResponse':
          instance.mastersCertVerificationResponse,
      'spouseUsername': instance.spouseUsername,
      'spouseName': instance.spouseName,
      'spouseMobile': instance.spouseMobile,
      'spouseEmail': instance.spouseEmail,
      'spouseBirthDate': instance.spouseBirthDate,
      'geographyType': instance.geographyType,
      'dataDigest': instance.dataDigest,
      'authenticationLevel': instance.authenticationLevel,
      'surveyRole': instance.surveyRole,
      'surveyManagerUsername': instance.surveyManagerUsername,
      'otpValue': instance.otpValue,
      'otpCreatedDate': instance.otpCreatedDate,
      'otpCreatedAt': instance.otpCreatedAt,
      'otpExpiredDate': instance.otpExpiredDate,
      'otpExpiredAt': instance.otpExpiredAt,
      'countOtpUse': instance.countOtpUse,
      'fatherUsername': instance.fatherUsername,
      'motherUsername': instance.motherUsername,
      'personNameLocalLang': instance.personNameLocalLang,
      'fatherNameLocalLang': instance.fatherNameLocalLang,
      'motherNameLocalLang': instance.motherNameLocalLang,
      'roles': instance.roles,
      'roleGroup': instance.roleGroup,
      'roleGroupLevel': instance.roleGroupLevel,
      'roleLevel': instance.roleLevel,
      'role': instance.role,
      'dirtyVersion': instance.dirtyVersion,
      'appToken': instance.appToken,
      'appTokenCreatedAt': instance.appTokenCreatedAt,
      'appTokenCreatedOn': instance.appTokenCreatedOn,
      'userImg': instance.userImg,
      'userHashInfo': instance.userHashInfo,
      'userImgHash': instance.userImgHash,
      'nidStatus': instance.nidStatus,
      'passportStatus': instance.passportStatus,
      'mastersCertificateStatus': instance.mastersCertificateStatus,
      'bachelorCertificateStatus': instance.bachelorCertificateStatus,
      'hscCertificateStatus': instance.hscCertificateStatus,
      'sscCertificateStatus': instance.sscCertificateStatus,
      'birthCertificateStatus': instance.birthCertificateStatus,
      'tinCertificateStatus': instance.tinCertificateStatus,
      'drivingLicenseStatus': instance.drivingLicenseStatus,
      'pointOffice': instance.pointOffice,
      'pointResidence': instance.pointResidence,
      'pointHome': instance.pointHome,
      'masterViewModel': instance.masterViewModel,
      'employeeRole': instance.employeeRole,
      'enabled': instance.enabled,
      'active': instance.active,
      'publicUser': instance.publicUser,
      'locationTraceEnabled': instance.locationTraceEnabled,
      'nidDocUploaded': instance.nidDocUploaded,
      'taxDocUploaded': instance.taxDocUploaded,
      'passportDocUploaded': instance.passportDocUploaded,
      'sscCertUploaded': instance.sscCertUploaded,
      'hscCertUploaded': instance.hscCertUploaded,
      'bachelorCertUploaded': instance.bachelorCertUploaded,
      'mastersCertUploaded': instance.mastersCertUploaded,
      'nidNoVerified': instance.nidNoVerified,
      'passportNoVerified': instance.passportNoVerified,
      'licenseDocUploaded': instance.licenseDocUploaded,
      'licenseNoVerified': instance.licenseNoVerified,
      'birthCertDocUploaded': instance.birthCertDocUploaded,
      'birthCertNoVerified': instance.birthCertNoVerified,
      'taxNoVerified': instance.taxNoVerified,
      'sscCertVerified': instance.sscCertVerified,
      'hscCertVerified': instance.hscCertVerified,
      'bachelorCertVerified': instance.bachelorCertVerified,
      'mastersCertVerified': instance.mastersCertVerified,
      'employed': instance.employed,
      'sscCompleted': instance.sscCompleted,
      'hscCompleted': instance.hscCompleted,
      'bachelorCompleted': instance.bachelorCompleted,
      'mastersCompleted': instance.mastersCompleted,
    };
